KillerApp/Controllers/AanpassenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic;
using killerAppSemester2.Models;

namespace KillerApp.Controllers
{
    public class AanpassenController : Controller
    {
        static AanpassingService serv = new AanpassingService();
        static UserService us = new UserService();
        // GET: Aanpassen
        public ActionResult Back()
        {
            return RedirectToAction("Details","User", new { @id = Convert.ToInt32(Session["autoid"]) });
        }
        public ActionResult OptiesAanpassen()
        {
            return View();
        }
        public ActionResult MTAanpassen(List<MotorTransmissie> mts)
        {
            if (mts == null)
            {
                int x = Convert.ToInt32(Session["autoid"]);
                List<MotorTransmissie> Mts = serv.GeefMtsVoorAanpassing(Convert.ToInt32(Session["autoid"]));
                return View(Mts);
            }
            return View(mts);
        }
        public ActionResult UitvoeringAanpassen(List<Uitvoering> uvs)
        {
            if(uvs == null) { 
            List<Uitvoering> uitvoeringen = serv.GeefUvsVoorUitvoeringen(Convert.ToInt32(Session["autoid"]));
            return View(uitvoeringen);
            }
            return View(uvs);
        }
        public ActionResult ModelAanpassen()
        {
            List<Model> Ms = serv.GeefMsVoorAanpassing(Convert.ToInt32(Session["autoid"]));
            return View(Ms);
        }
        public ActionResult VervangeMT(int MTID)
        {
            serv.VervangMt(MTID, Convert.ToInt32(Session["autoid"]));
            return RedirectToAction("Details", "User", new { @id = Convert.ToInt32(Session["autoid"]) });
        }
        public ActionResult VervangUV(string UVNaam)
        {
            List<MotorTransmissie> Mts = us.GeefAlleMTS(UVNaam);
            return RedirectToAction("MTAanpassen", Mts);
        }
        public ActionResult VervangM(string MNaam)
        {
            List<Uitvoering> UVs = us.GeefAlleUivoeringen(MNaam);
            return RedirectToAction("UitvoeringAanpassen", UVs);
        }
    }
}

KillerApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Logic;
using killerAppSemester2.Models;

namespace KillerApp.Controllers
{
    public class UserController : Controller
    {
        static LoginService ls = new LoginService();
        static UserService us = new UserService();
        //als je naam en wachtwoord juist zijn dan ga je na de lijst anders opnieuw proberen
        [HttpPost]
        public ActionResult Login(User user)
        {
            user.Id = ls.Login(user.Gebruikersnaam, user.Wachtwoord);
            if (user.Id == 0)
            {
                return View();
            }
            else
            {
                Session["user"] = user;
                return RedirectToAction("Index");
            }
        }
        //ziet lijst van auto's van de user na dat hij is ingelogd d.m.v. user sessie
        public ActionResult Index()
        {
            
            List<Auto> autos = new List<Auto>();
            autos = us.geefAlleAutosVan((Session["user"] as User).Id);
            return View(autos);
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        //laat details zien van één auto kan ook opties toevoegen en dingen aanpassen vanaf details view
        public ActionResult Details(int id)
        {
            Auto auto =us.geefAllesVanAuto(id);
            Session["autoid"] = id;
            return View(auto);
        }
        //..
        public ActionResult Verwijder(int id)
        {
            us.VerwijderAuto(id);
            return RedirectToAction("Index");
        }
        //gaat naar de controller samenstellen waar je een auto kan samenstellen
        public ActionResult NieuweAuto()
        {
            return RedirectToAction("KiesMerk","Samenstellen");
        }
        //maakt sessie autoid aan
        public ActionResult VoegExtrasToe()
        {
            return View();
        }
        //weergeeft de view voor het kiezen van accesoires
        public ActionResult VOpties()
        {
            
            List<Optie> opties = us.GeefAlleOptiesVoor(Convert.ToInt32(Session["autoid"]));
            return View(opties);
        }
        //voegt optie toe aan auto
        public ActionResult VOptie(int id)
        {
            
            us.VoegOptieToe(id, Convert.ToInt32(Session["autoid"]));
            return RedirectToAction("Index");
        }

        //verwijdert sessie en gaat terug na lijst van auto's
        public ActionResult Stop()
        {
            Session.Remove("autoid");
            return RedirectToAction("Index");
        }
        public ActionResult VerwijderOpties()
        {
            List<Optie> opts = us.GeefAlleOptiesVan(Convert.ToInt32(Session["autoid"]));
            return View(opts);
        }
        public ActionResult VerwijderOptie(int id)
        {
            us.VerwijderOptie(id, Convert.ToInt32(Session["autoid"]));
            return RedirectToAction("Index");
        }
        public ActionResult KiesWatAanpassen()
        {
            int autoid = Convert.ToInt32(Session["autoid"]);
            return View();
        }
    }
}

KillerApp/Views/User/Details.cshtml
@using killerAppSemester2.Models
@model Auto
@{
    ViewBag.Title = "Details";
}


<h2>Details van @Model.Naam</h2>

<h3>Merk</h3>
<ul>
    <li>@Model.merk.Naam</li>
    <li><img src=@Model.merk.Filenaam style=height:100px; /></li>
</ul>
<h3>Model</h3>
<ul>
    <li>@Model.Model.Naam</li>
    <li>Prijs is €@Model.Model.Prijs</li>
    <li><img src=@Model.Model.Filenaam /></li>
</ul>
<h3>Uitvoering</h3>
<ul>
    <li>@Model.Uitvoering.Naam</li>
    <li>prijs is €@Model.Uitvoering.Prijs</li>
    <li>@Model.Uitvoering.Beschrijving</li>
</ul>
<h3>MotorTransmissie</h3>
<ul>
    <li>@Model.MotorTransmissie.Naam</li>
    <li>prijs is €@Model.MotorTransmissie.Prijs</li>
    <li>Liter\100km: @Model.MotorTransmissie.LiterPer100</li>
    <li>paardenkracht: @(Model.MotorTransmissie.Paardenkracht)pk</li>
</ul>
<h3>Kleur</h3>
<ul>
    <li>Kleur is @Model.Kleur</li>
</ul>

@if (Model.opties.Count != 0)
{
    <h3>Opties</h3>
    <ul>
        @foreach (Optie o in Model.opties)
        {
        <li>@o.Naam</li>
        <li>@o.Beschrijving</li>
        <li>prijs is €@o.Prijs</li>
        <li><img src=@o.Filepath /></li>
        }
    </ul>
}
<h2 style="color:red">TotaalPrijs: €@Model.Prijs</h2>

<h3><a href=@Url.Action("OptiesAanpassen","Aanpassen")>Pas iets aan</a></h3>
<h3><a href=@Url.Action("VoegExtrasToe")>Beheer Opties</a></h3>

KillerApp/Views/User/Index.cshtml
@using killerAppSemester2.Models 
@model List<Auto>
@{
    ViewBag.Title = "Index";
}

<h2>Uw Auto's</h2>

<p>
    <ul>@foreach (Auto a in Model)
    {
        <li>@a.Naam 
        <button class="btn-default"><a href=@Url.Action("Details","User", new { @id = a.Id })>datails</a></button>
        <button class="btn-default"><a href=@Url.Action("Verwijder","User", new { @id = a.Id })>Verwijder Auto</a></button>
        </li>
    }
    </ul>

</p>

<p>
    <button class="btn-default"><a href=@Url.Action("NieuweAuto")>Nieuwe Auto samenstellen</a></button>
</p>

<style>
    button{
        margin-left: 25px !important;
    }
</style>

KillerApp/Views/User/Login.cshtml
@using killerAppSemester2.Models 
@model User
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<form method="post">
<p>
    <label for="Gebruikersnaam">Gebruikersnaam: </label>
    <input type="text" name="Gebruikersnaam" />
</p>
<p>
    <label for="Wachtwoord">Wachtwoord: </label>
    <input type="password" name="Wachtwoord" />
</p>
<p>
    <label for="Bevestig"></label>
    <input name="Bevestig" type="submit" class="btn-group-lg" value="Login"/>
</p>
</form>

KillerApp/Views/User/VAccessoires.cshtml
@using killerAppSemester2.Models
@model List<Accessoire>
@{
    ViewBag.Title = "Vaccessoires";
}

<h2>Accessoire toevoegen</h2>
@foreach (Accessoire a in Model)
{
    <ul>
        <li>@a.Naam</li>
        <li>@a.Beschrijving</li>
        <li>Prijs €@a.Prijs</li>
        <li><img src=@a.Filepath /></li>
        <li><a href=@Url.Action("VAccessoire", new { id = a.Id })>Voeg toe aan uw auto</a></li>
    </ul>
}
<h5><a href=@Url.Action("Stop")>terug</a></h5>

KillerApp/Views/User/VOpties.cshtml
@using killerAppSemester2.Models
@model List<Optie>
@{ 
    ViewBag.Title = "VOpties";
}

<h2>Opties toevoegen</h2>
@foreach (Optie o in Model)
{
<ul>
    <li>@o.Naam</li>
    <li>@o.Beschrijving</li>
    <li>Prijs €@o.Prijs</li>
    <li><img src=@o.Filepath /></li>
    <li><a href=@Url.Action("VOptie", new { id = o.Id })>Voeg toe aan uw auto</a></li>
</ul>
}
<h5><a href=@Url.Action("Stop")>terug</a></h5>

KillerApp/Views/User/VerwijderOpties.cshtml
@using killerAppSemester2.Models
@model List<Optie>
@{
    ViewBag.Title = "VerwijderOpties";
}

<h2>VerwijderOpties</h2>

@foreach (Optie o in Model)
{
    <ul>
        <li>@o.Naam</li>
        <li>@o.Beschrijving</li>
        <li>Prijs €@o.Prijs</li>
        <li><img src=@o.Filepath /></li>
        <li><a href=@Url.Action("VerwijderOptie", new { id = o.Id })>Verwijder van uw auto</a></li>
    </ul>
}
<h5><a href=@Url.Action("Stop")>terug</a></h5>

KillerApp/Views/User/VoegExtrasToe.cshtml
@{
    ViewBag.Title = "VoegExtrasToe";
}

<h2>Voeg extras toe</h2>
<h4><a href=@Url.Action("VOpties")>Voeg opties toe</a></h4>
<h4><a href=@Url.Action("VerwijderOpties")>Verwijder opties</a></h4>
<p>

</p>
<h5><a href=@Url.Action("Stop")>terug</a></h5>